account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('', views.landing_page, name='landing_page'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

anglais/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flashcard/', include('flashcard.urls')), #include all urls of flashcards app
    path('', include('account.urls')),
    path('english_mastermind/', include('english_mastermind.urls')),
    path('carolina/', include('carolina.urls')),
    path('social-auth', include('social_django.urls', namespace='social')), 
]

carolina/urls.py
from django.urls import path
from . import views

app_name = 'carolina'

urlpatterns = [
    path('', views.index, name='index'),

]

english_mastermind/urls.py
from django.urls import path
from . import views

app_name = 'english_mastermind'

urlpatterns = [
    path('', views.chatbot_mastermind, name='index'),

]

flashcard/urls.py
from django.urls import path 

from . import views
from django.conf import settings 
from django.conf.urls.static import static
from .views import StudySetWordUpdateView


app_name = 'flashcard'

urlpatterns = [
    # path('', views.home_view, name = 'home'),
    # path('', views.flash_card_home_view , name = "flash_card_home_view"),
    
    # tạo ra một studyset mới 
    path('new_studyset/', views.new_studyset, name="new_studyset"), 
    path('update/<int:pk>' , StudySetWordUpdateView.as_view(), name="update_studyset"), 
    path('delete-word/<int:form_id>/<int:word_id>', views.delete_word, name = 'delete_word'), 
    path('', views.studysets, name="studysets"),
    path('new_word/<int:id>',views.new_word, name = "new_word"),
    path('delete-studyset/<int:id>', views.delete_studyset, name= "delete_studyset"), 
    path('edit-word/<int:form_id>/<int:word_id>', views.edit_word, name="edit_word"), 
    path('learn/<int:id>',  views.learn, name='learn'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Profile(models.Model): 
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank=True, null=True)

    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .form import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib import messages


# Create your views here.

@login_required
def dashboard(request): 
    return render(request, 'dashboard.html')


def landing_page(request): 
    return render(request, 'landing_page.html')



def user_login(request): 
    """Hàm view của user login"""
    if request.method == 'POST': 
        form = LoginForm(data=request.POST)

        if form.is_valid(): 
            cd = form.cleaned_data
            user = authenticate(
                request, 
                username=cd['username'], 
                password=cd['password']
            )


            if user is not None: 
                if user.is_active: 
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else: 
                    return HttpResponse('Disabled account')
            else : 
                return HttpResponse('Invalid login')

    else : 
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

                  
def register(request): 

    if request.method == 'POST':

        userform = UserRegistrationForm(data=request.POST)

        if userform.is_valid(): 

            new_user = userform.save(commit=False)

            new_user.set_password(userform.cleaned_data['password'])

            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'account/register_done.html', {'new_user': new_user})
        
    userform = UserRegistrationForm()

    return render(request, 'account/register.html', {'userform': userform})

@login_required
def edit(request): 

    if request.method == 'POST': 
        user_form = UserEditForm(instance=request.user, data=request.POST)

        profile_form = ProfileEditForm(
                    instance=request.user.profile,
                    data=request.POST,
                    files=request.FILES)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile update', 'successfully')
        else: 
            messages.error(request, "Profile update", 'unsuccessfully')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

account/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta property="og:title" content="Spotless Honorable Dove" /><meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" /><meta
      charset="utf-8" /><meta
      property="twitter:card"
      content="summary_large_image" /><style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }</style>
      <style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }</style>
  <link href="{% static 'css/base1.css' %}" rel="stylesheet">
  <link
      rel="stylesheet"
      href="https://unpkg.com/animate.css@4.1.1/animate.css" /><link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
      data-tag="font" /><link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font" /><link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&amp;display=swap"
      data-tag="font" /><link
      rel="stylesheet"
      href="https://unpkg.com/@teleporthq/teleport-custom-scripts/dist/style.css" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" /><div>
  <link href="{% static 'css/base_navbar.css' %}" rel="stylesheet" />
</head>
<body>
  
  <div class="home-container">
    <header data-thq="thq-navbar" class="home-navbar-interactive">
      {% if request.user.is_authenticated %}
        <form action="{% url 'dashboard' %}" method="get">
          <button type="submit">
              <img src="{% static 'img/anglais-1500h.png' %}" alt="Button Image" class="home-image logo">
          </button>
        </form>
      {% else %} 
        <form action="{% url 'landing_page' %}" method="get">
          <button type="submit">
              <img src="{% static 'img/anglais-1500h.png' %}" alt="Button Image" class="home-image logo">
          </button>
        </form>
      {% endif %}

      <div data-thq="thq-navbar-nav" class="home-desktop-menu">
        <nav class="home-links">
          <span class="home-text01 hide_on_small">About</span>
      
          {% if request.user.is_authenticated %}
            <span {% if section == "dashboard" %}{% endif %} >
              <a class = "home-text01 hide_on_small" href="{% url 'dashboard' %}">Dashboard</a>
            </span>
            <span {% if section == 'flashcard' %}class="selected"{% endif %}>
              <a class="home-text01 hide_on_small" href="{% url 'flashcard:studysets' %}">Flashcard</a>
            </span> 
              
            
            <span {% if section == "english master mind" %}class="selected"{% endif %} >

              <a class="home-text02 hide_on_small" href="{% url 'english_mastermind:index' %}">Mastermind</a>
            </span> 
              
            
            <span class="home-text03 hide_on_small">Blog</span>
            {% comment %} <span class="home-text03">Hello {{ request.user.first_name|default:request.user.username }},</span> {% endcomment %}
          {% endif %}
        </nav>
      
      <span class="user">
        {% if request.user.is_authenticated %}
          <div class="home-buttons home-text01">
            <form action="{% url 'edit' %}" method="get">
              <button class="button">Account</button>
            </form> 
          </div>
        {% else %}
          <div class="home-buttons home-text01">
            <form action="{% url 'login' %}" method="get">
              <button class="button">Login</button>
            </form> 
          </div>
        {% endif %}
      </span>

      {% if request.user.is_authenticated %}
      <div class="home-buttons home-text01">
        <form action="{% url 'logout' %}" method="get">
          <button class="logout_button button">Logout</button>
        </form> 
      </div>
      {% endif %}

      
      <div data-thq="thq-burger-menu" class="home-burger-menu">
        <svg viewBox="0 0 1024 1024" class="home-icon">
          <path
            d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z"
          ></path>
        </svg>
      </div>
    </header>
  </div>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
          <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>
{% comment %} <div id="header">
    <span class="logo">Anglais</span>
    {% if request.user.is_authenticated %}
      <ul class="menu">
        <li {% if section == "dashboard" %}class="selected"{% endif %}>
          <a href="{% url 'dashboard' %}">My dashboard</a>
        </li>
        <li {% if section == 'flashcard' %}class="selected"{% endif %}>
          <a href="#">Images</a>
        </li>
        <li {% if section == "english master mind" %}class="selected"{% endif %}>
          <a href="#">People</a>
        </li>
      </ul>
    {% endif %}
    <span class="user">
      {% if request.user.is_authenticated %}
        Hello {{ request.user.first_name|default:request.user.username }},
        <a href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'edit' %}">Edit your accout</a>
      {% else %}
        <a href="{% url 'login' %}">Log-in</a>
      {% endif %}
    </span>
  </div> {% endcomment %}

account/templates/dashboard.html
{% extends 'base1.html' %}
{% load static %}


{% block title %} Dashboard {% endblock %} 
{% block content %}
<!DOCTYPE html>
<html lang="en"
  >
  <head
    ><title>Stark Babyish Gazelle</title
    ><meta property="og:title" content="Stark Babyish Gazelle" /><meta
      name="viewport"
      content="width=device-width, initial-scale=1.0" /><meta
      charset="utf-8" /><meta
      property="twitter:card"
      content="summary_large_image" /><style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6,figure,blockquote,figcaption {  margin: 0;  padding: 0;}button {  background-color: transparent;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }</style
    ><style data-tag="default-style-sheet">
      html {
        font-family: Inter;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.15;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }</style
    ><link
      rel="stylesheet"
      href="https://unpkg.com/animate.css@4.1.1/animate.css" /><link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
      data-tag="font" /><link
      rel="stylesheet"
      href="https://unpkg.com/@teleporthq/teleport-custom-scripts/dist/style.css" /></head
  ><body
    ><link rel="stylesheet" href="{% static 'css\dashboard\style_dashboard.css' %}" /><div
      ><link href="{% static 'css\dashboard\index_dashboard.css' %}" rel="stylesheet" /><div class="sub-home-container"
        ><div class="home-banner"
          ><h1 class="home-text">What would you like to do today?</h1
          ><span class="home-text1"
            ><span
              >Feel free to choose any of the features we have to offer!</span
            ><br /></span
          ><span></span></div
        ><div class="home-blog"
          ><div class="home-container1"
            ><a href = "{% url 'flashcard:studysets' %}">
            <div
              class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3" 
              ><img
                alt="image"
                src="{% static 'img\external\1.png' %}"
                image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000"
                class="blog-post-card2-image"
              /><div class="blog-post-card2-container"
                ><div class="blog-post-card2-container1"
                  ><span class="blog-post-card2-text"
                    ><span>Feature 1</span></span
                  ><span class="blog-post-card2-text1"
                    ></span
                  ></div
                ><h1 class="blog-post-card2-text2"><a href="{% url 'flashcard:studysets' %}"><span>C.R.R</span></a></h1
                ><span class="blog-post-card2-text3"
                  ><span
                    >Create your own vocabulary studysets. Review your
                    knowledge. Rinse and repeat. This is the first and the main
                    feature that we would like to offer.</span
                  ></span
                ><div class="blog-post-card2-container2"
                  ></div
                ></div
              ></div
              ></a
            ></div
          
          ><div class="home-container1"
          ><a href="{% url 'english_mastermind:index' %}"
            ><div
              class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3" 
              ><img
                alt="image"
                src="{% static 'img\external\2.png' %}"
                image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000"
                class="blog-post-card2-image"
              /><div class="blog-post-card2-container"
                ><div class="blog-post-card2-container1"
                  ><span class="blog-post-card2-text"
                    ><span>Feature 2</span></span
                  ><span class="blog-post-card2-text1"
                    ></span
                  ></div
                ><h1 class="blog-post-card2-text2"><span>Carolina</span></h1
                ><span class="blog-post-card2-text3"
                  ><span
                    >Who is Carolina, I hear you ask? Say hello to your family
                    friendly AI essay reviewer. If you have any paragraph that
                    you would like to check for quality, ask her right
                    away!</span
                  ></span
                ><div class="blog-post-card2-container2"
                  ></div
                ></div
              ></div
            ></div
          ></a
          ><a href="{% url 'carolina:index' %}"
            ><div
              class="blog-post-card2-blog-post-card blog-post-card2-root-class-name2"
              ><img
                alt="image"
                src="{% static 'img\external\3.png' %}"
                image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000"
                class="blog-post-card2-image"
              /><div class="blog-post-card2-container"
                ><div class="blog-post-card2-container1"
                  ><span class="blog-post-card2-text"><span>Feature 3</span></span
                  ><span class="blog-post-card2-text1"
                    ></span
                  ></div
                ><h1 class="blog-post-card2-text2"
                  ><span>Cha biet la cai gi</span></h1
                ><span class="blog-post-card2-text3"
                  ><span
                    >ai do bao vinh pham ghi noi dung vao day di, toi cung cha
                    biet cai app 3 la cai gi nua hehe, nho ghi dai ra nhe khong la
                    loi html</span
                  ></span
                ><div class="blog-post-card2-container2"
                  ></div
                ></div
              ></div
            ></div
          ></a>
        <div class="home-banner1">
          <footer class="home-footer"
            ><img
              alt="logo"
              src="{% static 'img\external\anglais_invert.png' %}"
              class="home-image"
            />
          </footer>
        </div>
        </div
      ></div
    >
  </body>
</html>
{% endblock %}