account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('', views.landing_page, name='landing_page'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

anglais/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flashcard/', include('flashcard.urls')), #include all urls of flashcards app
    path('', include('account.urls')),
    path('english_mastermind/', include('english_mastermind.urls')),
    path('carolina/', include('carolina.urls')),
    path('social-auth', include('social_django.urls', namespace='social')), 
]

flashcard/urls.py
from django.urls import path 

from . import views
from django.conf import settings 
from django.conf.urls.static import static
from .views import StudySetWordUpdateView


app_name = 'flashcard'

urlpatterns = [
    # path('', views.home_view, name = 'home'),
    # path('', views.flash_card_home_view , name = "flash_card_home_view"),
    
    # tạo ra một studyset mới 
    path('new_studyset/', views.new_studyset, name="new_studyset"), 
    path('update/<int:pk>' , StudySetWordUpdateView.as_view(), name="update_studyset"), 
    path('delete-word/<int:form_id>/<int:word_id>', views.delete_word, name = 'delete_word'), 
    path('', views.studysets, name="studysets"),
    path('new_word/<int:id>',views.new_word, name = "new_word"),
    path('delete-studyset/<int:id>', views.delete_studyset, name= "delete_studyset"), 
    path('edit-word/<int:form_id>/<int:word_id>', views.edit_word, name="edit_word"), 
    path('learn/<int:id>',  views.learn, name='learn'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone 
# Create your models here.



class Folders(models.Model): 
    """Class dùng để biểu diễn đối tượng folder cho toàn bộ file """

    title = models.CharField(max_length=200)
    description = models.TextField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'folders') #author of the folder
    
    publish = models.DateTimeField(default = timezone.now())
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.title 
    

class StudySet(models.Model): 
    """Class dùng để biểu diễn tập từ vựng, nằm trong tập folder"""

    title = models.CharField(max_length = 200)
    description = models.TextField()
    # folder = models.ForeignKey(Folders, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    learning_time = models.IntegerField(default = 0)

    def __str__(self):  
        return self.title
    
class Word(models.Model): 
    """Class này dùng để biểu diễn """
    class  TypeOfWord(models.TextChoices): 
        ENGLISH = 'en'
        VIETNAMESE = 'vi'


    studyset = models.ForeignKey(StudySet, on_delete=models.CASCADE)
    ori_word = models.CharField(max_length = 30)
    trans_word = models.CharField(max_length = 150)

    or_lan = models.CharField(max_length = 3, choices = TypeOfWord.choices, default = TypeOfWord.ENGLISH)
    ne_lan = models.CharField(max_length = 3, choices = TypeOfWord.choices, default = TypeOfWord.VIETNAMESE)


    def __str__(self): 
        return self.studyset.title
    

flashcard/views.py
from typing import Any
from django.forms.forms import BaseForm
from django.shortcuts import render, redirect, get_object_or_404,  HttpResponseRedirect
from .form import WordFormset, SetForm, WordForm
from django.views.generic import ListView 

from .models import Word, StudySet
from django.contrib import  messages

from django.urls import reverse,  reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import SingleObjectMixin
from  django.views.generic import FormView, UpdateView
from django.db import transaction

# Create your views here.

@login_required
def home_view(request): 
    return  render(request, 'base.html')


@login_required
def flash_card_home_view(request): 
    return render(request, 'flashcard/home_view.html')

@login_required
def delete_word(request, form_id, word_id):
    '''Hàm view thực hiện xóa word trong form - sử dụng button'''
    word = get_object_or_404(Word, id=word_id)

    if request.method == 'POST': 
        word.delete()
        return redirect('flashcard:update_studyset', id=form_id)
    else : 
        return JsonResponse({'status': 'error'}, status = 400)
    


@login_required
def delete_studyset(request, id): 
    '''Hàm xóa studyset tại node delete của list_studyset'''
    studyset = get_object_or_404(StudySet, pk=id)

    if request.method == "POST": 
        studyset.delete()

        return HttpResponseRedirect('/flashcard/')
    
    return redirect('flashcard:studysets')



@login_required
def new_studyset(request): 
    '''Hàm tạo studyset mới'''
    if request.method == 'POST':
            form = SetForm(request.POST)
            if form.is_valid():
                studyset = form.save(commit=False)

                studyset.user = request.user 

                studyset.save()
                if 'save' in request.POST:
                    # Nếu người dùng nhấn nút "Save"
                    return redirect('flashcard:studysets')
                elif 'saveandadd' in request.POST:
                    # Nếu người dùng nhấn nút "Save and Add Card"
                    # Chuyển hướng đến URL với ID của studyset vừa được tạo
                    return redirect(reverse('flashcard:new_word', args=[studyset.id]))
    else:
        form = SetForm()

    return render(request, 'flashcard/new_studyset.html', {'form': form})

@login_required
def new_word(request, id): 
    '''Tạo formset mới'''
    try :  
        studyset = StudySet.objects.get(id = id)

    except StudySet.DoesNotExist: 
        return redirect('flashcard:studysets')
    

    if request.method != "POST": 
        formset = WordFormset(instance = studyset)

    else : 
        formset = WordFormset(data = request.POST, instance = studyset)

        if formset.is_valid(): 

            formset.save()

        return redirect('flashcard:studysets')

    context = {'formset': formset}

    return render(request, 'flashcard/new_word.html', context = context)


# @login_required
# def update_studyset(request,  id): 
#     '''Hàm update thông tin của formset '''
#     studyset = get_object_or_404(StudySet, id=id)
#     form = SetForm(instance= studyset)
    
#     words = Word.objects.all( ).filter (studyset = id)
#     if request.method == "POST": 
#         form = SetForm(data = request.POST, instance = studyset)
       
#         if form.is_valid() :


#             form.save()
#             if 'save' in request.POST: 
#                 return redirect('flashcard:studysets')
#             elif 'addmore' in request.POST: 
#                 return redirect('flashcard:new_word', id=id)

#     return render(request, 'flashcard/edit_studyset.html', {'form': form, 'words': words})

@login_required
def edit_word(request, form_id, word_id): 

    word = get_object_or_404(Word, id = word_id )
    form = WordForm(instance=word)

    if request.method == "POST" :  
        form = WordForm(instance=word , data=request.POST)

        if form.is_valid(): 
            form.save()

            return redirect('flashcard:update_studyset', id=form_id)

    return render(request, 'flashcard/edit_word.html', {'form': form, 'word': word, 'form_id': form_id})



@login_required 
def studysets(request): 

    studysets = StudySet.objects.filter(user= request.user)

    context = {'studysets': studysets}


    return render(request, 'flashcard/studysets.html', context)


@login_required
def learn(request, id):

    studysets = get_object_or_404(StudySet, id = id)
    words = Word.objects.all().filter(studyset = id)

    if len(words) == 0  : 
        return render(request, 'flashcard/error.html', {'studysets' : studysets})

    current_indx = int(request.GET.get("index", 0))

    next_indx = (current_indx + 1) % len(words)

    prev_indx = (current_indx - 1) % len(words)
    
    word_num =  len(words)
    context = {
        "studysets" : studysets, 
        "curr_word" : words[current_indx],
        "next_indx" : next_indx,
        "prev_indx" : prev_indx, 
        "word_num" : word_num, 
        "curr_indx" : current_indx
    }

    return render(request, 'flashcard/learn.html', context) 




class StudySetWordUpdateView(UpdateView) : 

    model = StudySet
    form_class = SetForm
    template_name = 'flashcard/edit_studyset.html'
    login_required = True 
    success_url = reverse_lazy('flashcard:studysets')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['word_formset'] = WordFormset(self.request.POST, instance=self.object)
        else:
            data['word_formset'] = WordFormset(instance=self.object)
        return data


    def form_valid(self, form):
        
        context = self.get_context_data()
        word_formset = context['word_formset']
        
        with transaction.atomic():
            if word_formset.is_valid():
                
                word_formset.instance = self.object
                word_formset.save()
            else : print(word_formset.errors)
            self.object = form.save()
            
        return super().form_valid(form)
    

    def form_invalid(self, form, word_formset):
        return self.render_to_response(
            self.get_context_data(form=form, word_formset=word_formset)
        )
   

    

flashcard/templates/flashcard/edit_studyset.html
{% extends "base1.html" %}
{% load static %}

{% block title %}Edit StudySet{% endblock %}

{% block content %}
  
  <!DOCTYPE html>
  <html lang="en">
    
    <body>
        <link rel="stylesheet" href="{% static 'styles\general\general.css' %}" />
        <link rel="stylesheet" href="{% static 'styles\edit_studyset\edit_studyset.css' %}" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <div class="outer_most">
        <h1 class="header">Edit studyset </h1>
        
        <form method="post" id="wordform">
            {% csrf_token %}
            {{ word_formset.management_form }}
        
          <!-- Studyset form fields -->
            <div class="form-style">
                <label for="id_title" class="texts">Title:</label> {{ form.title }}
                <label for="id_description" class="texts">Description:</label> {{ form.description }}
            </div>
      

          <!-- Word formset -->
            <div class="form-style words">
            <div id="words-container">
                <form method="post">
                    <table class="table">
                        <tr>
                            <th>Original Language</th>
                            <th>Original Word</th>
                            <th>New Language</th>
                            <th>Translated Word</th>
                            <th>Actions</th>
                        </tr>
                    
                        {% for word_form in word_formset %}
                        <tr class="word-form">
                            {% for hidden in word_form.hidden_fields %}
                            {{ hidden }}
                            {% endfor %}
                            <td>{{ word_form.or_lan }}</td>
                            <td>{{ word_form.ori_word }}</td>
                            <td>{{ word_form.ne_lan }}</td>
                            <td>{{ word_form.trans_word }}</td>
                            <td><button type="button" class="delete-form-btn">Delete</button></td>
                        </tr>
                        {% if word_form.errors %}
                        <tr>
                            <td colspan="5">{{ word_form.errors }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                    
                </form>
                
            </div>
            <button type='button' id="add-form-btn" class="delete-form-btn">Add another</button>
                <input type="submit" value="Save">
            </div>
            
        </form>


        <script id="empty-form-template" type="text/template">
          <tr class="word-form">
              
              <td>{{ word_formset.empty_form.or_lan.as_widget }}</td>
              <td>{{ word_formset.empty_form.ori_word.as_widget }}</td>
              <td>{{ word_formset.empty_form.ne_lan.as_widget }}</td>
              <td>{{ word_formset.empty_form.trans_word.as_widget }}</td>
              <td><button type="button" class="delete-form-btn">Delete</button></td>
          </tr>
        </script>
        
        <script>
          $(document).ready(function() {
              var formsetContainer = $('#words-container table');
              var emptyFormTemplate = $('#empty-form-template').text();
              var totalForms = $('#id_{{ word_formset.prefix }}-TOTAL_FORMS');
              console.log('Total forms:', totalForms.val());
      
              // Hàm cập nhật index cho các phần tử form
              function updateElementIndex(el, prefix, index) {
                  var idRegex = new RegExp('(' + prefix + '-\\d+)');
                  var replacement = prefix + '-' + index;
                  if (el.id) el.id = el.id.replace(idRegex, replacement);
                  if (el.name) el.name = el.name.replace(idRegex, replacement);
              }
      
              // Thêm form mới
              $('#add-form-btn').click(function() {
                  
                  var newForm = emptyFormTemplate.replace(/__prefix__/g, totalForms.val());
                  formsetContainer.append(newForm);
                  totalForms.val(parseInt(totalForms.val()) + 1);
              });
      
              // Xóa form hiện tại
              formsetContainer.on('click', '.delete-form-btn', function() {
                  $(this).closest('tr').remove();
                  var forms = formsetContainer.find('tr.word-form');
                  totalForms.val(forms.length);
                  forms.each(function(index, element) {
                      updateElementIndex(element, '{{ word_formset.prefix }}', index);
                  });
              });
          });
      </script>
      

      </div>
    </body>
  </html>
{% endblock %}

flashcard/templates/flashcard/error.html
{% extends "base1.html" %}
{% load static %}

{% block content %}

    <h1> Opps! </h1>

    <p> You don't have any word in your studyset </p>
    <a href="{% url  'flashcard:new_word' studysets.id %}"> Add another </a>
    


{% endblock %}

flashcard/templates/flashcard/learn.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Frugal Pleased Eel</title>
  <meta property="og:title" content="Frugal Pleased Eel" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta charset="utf-8" />
  <meta property="twitter:card" content="summary_large_image" />

  <style data-tag="reset-style-sheet">
    html {
      line-height: 1.15;
    }
    body {
      margin: 0;
    }
    * {
      box-sizing: border-box;
      border-width: 0;
      border-style: solid;
    }
    p, li, ul, pre, div, h1, h2, h3, h4, h5, h6, figure, blockquote, figcaption {
      margin: 0;
      padding: 0;
    }
    button {
      background-color: transparent;
    }
    button, input, optgroup, select, textarea {
      font-family: inherit;
      font-size: 100%;
      line-height: 1.15;
      margin: 0;
    }
    button, select {
      text-transform: none;
    }
    button, [type="button"], [type="reset"], [type="submit"] {
      -webkit-appearance: button;
    }
    button::-moz-focus-inner, [type="button"]::-moz-focus-inner, [type="reset"]::-moz-focus-inner, [type="submit"]::-moz-focus-inner {
      border-style: none;
      padding: 0;
    }
    button:-moz-focus, [type="button"]:-moz-focus, [type="reset"]:-moz-focus, [type="submit"]:-moz-focus {
      outline: 1px dotted ButtonText;
    }
    a {
      color: inherit;
      text-decoration: inherit;
    }
    input {
      padding: 2px 4px;
    }
    img {
      display: block;
    }
    html {
      scroll-behavior: smooth;
    }
  </style>

  <style data-tag="default-style-sheet">
    html {
      font-family: Inter;
      font-size: 16px;
    }
    body {
      font-weight: 400;
      font-style: normal;
      text-decoration: none;
      text-transform: none;
      letter-spacing: normal;
      line-height: 1.15;
      color: var(--dl-color-gray-black);
      background-color: var(--dl-color-gray-white);
    }
  </style>

  <link rel="stylesheet" href="https://unpkg.com/animate.css@4.1.1/animate.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" data-tag="font" />
  <link rel="stylesheet" href="https://unpkg.com/@teleporthq/teleport-custom-scripts/dist/style.css" />
</head>

<body>
  <link rel="stylesheet" href="{% static 'styles\learn\style_learn.css' %}" />
  <div>
    <link href="{% static 'styles\learn\index_learn.css' %}" rel="stylesheet" />
    <div class="home-container">
      <div class="home-banner">
        <h1 class="home-text">Review time!</h1>
        <p class="home-heading"> {{ studysets.title }} </p>
        <img src="{% static 'images\external\bg8.png' %}" alt="image" class="home-image" />
      </div>

      
      <h2 class="home-text01">
        <span>Translate this from &lt;{{ curr_word.or_lan }}&gt; to &lt;{{ curr_word.ne_lan }}&gt;</span><br /><br class="home-text04" /><span> </span>
      </h2>
      <div class="home-blog1">
        <div class="home-container1">
          <div class="blog-post-card1-blog-post-card blog-post-card1-root-class-name3">
            <div class="blog-post-card1-container">
              <a href="?index={{ prev_indx }}">

                <img alt="profile" src="{% static 'images\external\left.png' %}" image_src="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fG1hbiUyMHBvcnRyYWl0fGVufDB8fHx8MTYyNjQzMTMwMw&amp;ixlib=rb-1.2.1&amp;h=1200" class="blog-post-card1-image"/>
              </a>
            </div>
          </div>
        </div>
        <span class="home-text09">{{ next_indx }}/{{ word_num }}  </span>
        <div class="home-container2">
          <div class="blog-post-card1-blog-post-card blog-post-card1-root-class-name1">
            <div class="blog-post-card1-container">
                <a href="?index={{ next_indx }}">

                  <img alt="profile" src="{% static 'images\external\right.png' %}" image_src="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fG1hbiUyMHBvcnRyYWl0fGVufDB8fHx8MTYyNjQzMTMwMw&amp;ixlib=rb-1.2.1&amp;h=1200" class="blog-post-card1-image"/>
                </a>
                
            </div>
          </div>
        </div>
      </div>


      {% comment %} <div class="home-blog">
        <div class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3">
          <img alt="image" src="{% static 'images\external\bg5.3.png' %}" image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000" class="blog-post-card2-image" />
        </div>
        <span class="home-text06">
          <span>{{ curr_word.ori_word }}</span><br />
        </span>
      </div>


      <div class="home-blog">
        <div class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3">
          <img alt="image" src="{% static 'images\external\bg5.3.png' %}" image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000" class="blog-post-card2-image" />
        </div>
        <span class="home-text06">
          <span>{{ curr_word.trans_word }}</span><br />
        </span>
      </div> {% endcomment %}
      
      <div class="flip-card">
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <div class="home-blog upper">
              <div class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3">
                <img alt="image" src="{% static 'images\external\bg5.3.png' %}" image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000" class="blog-post-card2-image" />
              </div>
              <span class="home-text06">
                <span>{{ curr_word.ori_word }}</span><br />
              </span>
            </div>
          </div>
          <div class="flip-card-back">
            <div class="home-blog lower">
              <div class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3">
                <img alt="image" src="{% static 'images\external\bg5.3.png' %}" image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000" class="blog-post-card2-image" />
              </div>
              <span class="home-text06">
                <span>{{ curr_word.trans_word }}</span><br />
              </span>
            </div>
          </div>
        </div>
      </div>



      <img src="{% static 'images\external\bg7.png' %}" alt="image" class="home-image1" />
    </div>
  </div>
  <script>
    function clicked(e) {
      console.log(e.target)
      if(e.target.matches('.blog-post-card2-image')) {
        console.log('yay')
        document.querySelector('.flip-card').classList.toggle('is-flipped');
        document.querySelector('.home-blog.upper').className = 'temp';
        document.querySelector('.home-blog.lower').className = 'home-blog upper';
        document.querySelector('.temp').className = 'home-blog lower';
        document.querySelector('.home-blog.lower').removeEventListener('click', clicked);
        document.querySelector('.home-blog.upper').addEventListener('click', clicked);
      }
    }
    document.querySelector('.home-blog.upper').addEventListener('click', clicked);
    
    
  </script>
</body>
</html>

flashcard/templates/flashcard/new_studyset.html
{% extends "base1.html" %}
{% load static %}

{% block title %}New StudySet{% endblock %}

{% block content %}
  
  <!DOCTYPE html>
  <html lang="en">
    <head></head>
    <body>
      <link rel="stylesheet" href="{% static 'styles\general\general.css' %}" />
      <link rel="stylesheet" href="{% static 'styles\new_studyset\new_studyset.css' %}" />
      <div class="outer_most">
      <h1 class="header">Create New StudySet</h1>

      <div class="card">
        <form action="{% url 'flashcard:new_studyset' %}" method="post" class="form-style">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" id="SaveandAddButton" name="saveandadd" value="Save and Add Card" class="btn save_button">
        </form>
      </div>
    
    </div>
    </body>
  </html>
{% endblock %}

flashcard/templates/flashcard/new_word.html
{% extends "base1.html" %}
{% load static %}

{% block title %}New Word{% endblock %}

{% block content %}
  
  <!DOCTYPE html>
  <html lang="en">
    <head></head>
    <body>
      <link rel="stylesheet" href="{% static 'styles\general\general.css' %}" />
      <link rel="stylesheet" href="{% static 'styles\new_word\new_word.css' %}" />
      <div class="outer_most">
        <h1 class="header">Add vocabulary</h1>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    
        <form method="post" id="wordform" class="form-style">
            
            {% csrf_token %}
            {{ formset.management_form }}
            
        
            <div id="formset-container">
                {% for form in formset %} 
                <div class="card">
                    <div class="formset-form">
                        <div class="language box">
                            <p>Original Language: {{form.or_lan}}</p>
                            <p>Original Word: </p> {{form.ori_word}}
                        </div>
                        <div class="translation box">
                            <p>New Language: {{form.ne_lan}}</p>
                            <p>Translated Word: </p> {{form.trans_word}}
                        </div>
                        
                            
                    </div>
                    <h1></h1>
                    <div class="del">
                        <button type="button" class="delete-form-btn btn btn-danger">Delete</button> 
                    </div>
                </div>
                {% endfor %}
            </div>
            <button type='button' id="add-form-btn" class="btn btn-success bottom_button"> Add another </button>
            <input type="submit" value="Submit" class="btn btn-primary bottom_button">
        </form>
        {% comment %} <button type='button' id="add-form-btn" class="btn btn-success bottom_button"> Add another </button>
        <input type="submit" value="Submit" class="btn btn-primary bottom_button"> {% endcomment %}
    


        <script id="empty-form-template" type="text/template">
    
            <div class="card">
                <div class="formset-form">
                    <div class="language box">
                        <p>Original Language: {{formset.empty_form.or_lan}}</p>
                        <p>Original Word: </p> {{formset.empty_form.ori_word}}
                    </div>
                    <div class="translation box">
                        <p>New Language: {{formset.empty_form.ne_lan}}</p>
                        <p>Translated Word: </p> {{formset.empty_form.trans_word}}
                    </div>
                    
                        
                </div>
                <h1></h1>
                <div class="del">
                    <button type="button" class="delete-form-btn btn btn-danger">Delete</button> 
                </div>
            </div>
    
        </script>
    
    
        
        <script>
            $(document).ready(function() {
    
                var totalForms = $('#id_{{ formset.prefix }}-TOTAL_FORMS');
    
                var formsetContainer = $('#formset-container'); 
    
                var emptyFormTemplate = $('#empty-form-template').text(); 
    
            
    
                // Hàm update lại index của form 
                function updateElementIdx(el, prefix, index) {
                    var idRegex = new RegExp('(' + prefix + '-\\d+)'); 
    
                    var replacement = prefix + '-' + index; 
    
                    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(idRegex, replacement)); 
    
                    if (el.id) el.id = el.id.replace(idRegex, replacement); 
    
                    if (el.name) el.name = el.name.replace(idRegex, replacement)
    
                }
    
                // Add form button 
    
                $('#add-form-btn').click(function() {
    
                    var newForm = emptyFormTemplate.replace(/__prefix__/g, totalForms.val()); 
                    formsetContainer.append(newForm); 
    
                    totalForms.val(parseInt(totalForms.val()) + 1); 
    
                }); 
    
                // Delete form button 
                formsetContainer.on('click', '.delete-form-btn', function() {
                    $(this).closest('.card').remove();
                    var forms = formsetContainer.find('.card'); 
    
                    $('#id_{{ formset.prefix }}-TOTAL_FORMS').val(forms.length); 
    
                    for (var i = 0, formCount = forms.length; i < formCount; i ++) {
                        updateElementIdx(forms.get(i), '{{ formset.prefix }}', i); 
                    }
    
    
                });
    
            }); 
    
        </script>
    </div>
    </body>
  </html>
{% endblock %}

flashcard/templates/flashcard/studysets.html
{% extends "base1.html" %}
{% load static %}

{% block title %}Workspace{% endblock %}

{% block content %}
  
  <!DOCTYPE html>
  <html lang="en">
    <head></head>
    <body>
      <link rel="stylesheet" href="{% static 'styles\general\general.css' %}" />
      <link rel="stylesheet" href="{% static 'styles\workspace\workspace.css' %}" />
      <div class="outer_most">
        <div class="header_card">
            {% comment %} <div class ="card-header card-header-secondary"> {% endcomment %}
                <h1 class="header">My Workspace</h1>
                <a href="{% url 'flashcard:new_studyset' %}" class="btn">Create new studyset</a>
            {% comment %} </div> {% endcomment %}
        </div>

            {% comment %} <ul> {% endcomment %}
            {% for studyset in studysets %}
                <div class="studyset">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="card-title">{{ studyset.title }}</h1>
                            <div class="buttons">
                                <div class="not_delete">
                                <a href="{% url 'flashcard:update_studyset' studyset.id %}" class="btn btn-primary">Edit</a>
                                <a href="{% url 'flashcard:learn' studyset.id %}" class="btn btn-success">Learn</a>
                                
                                </div>
                                <form action="{% url 'flashcard:delete_studyset' studyset.id %}" method="post" style="display: inline-block;">
                                    {% csrf_token %}
                                    <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this studyset?');">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

    
            {% comment %} </ul> {% endcomment %}

    
    </div>

    {% comment %}
    <script type="text/javascript">
        function learnStudySet(studyset) {
            if (studysetsLength === 0) {
                alert('Không có nội dung để học.');
            } else {
                window.location.href = `{% url 'flashcard:learn' studyset.id %}`;
            }
        }
    </script>
    {% endcomment %}
        


    </body>
  </html>
{% endblock %}